### PR TITLE
add weekly-ci action

### PR DESCRIPTION
**Pull request by ukulekek**
Signed-off-by: Evgeny Fedin <efedin@redhat.com>

### CODE REVIEW

**Comment by ukulekek** [comment]
This action will trigger the CI system to test the role every weekend. It will ensure the role didn't break because of dependencies and other factors while being inactively developed. See https://url.corp.redhat.com/1ab3ab1 for more details

**Comment by t184256** [comment]
Isn't there any simpler way? One that doesn't involve pushing empty commits and creating empty PRs?

**Comment by ukulekek** [comment]
@t184256, I'm afraid, there is no better solution with the existing CI infrastructure.  
We use BaseOS CI infrastructure, which runs gluetool as a pipeline system. The gluetool requires a testing artifact which is provided as PR data by the github module ([https://gitlab.com/testing-farm/gluetool-modules/-/blob/main/gluetool_modules_framework/infrastructure/github.py#L497](link)). So the first limitation is the PR is required to test the role. Even if it is possible to implement the ability of gluetool test just a main branch, here comes the second limitation. We need to report the results of testing somewhere that it is visible for both Red Hat and external contributors. The most convenient, and the only implemented way, for now, is through PR statuses. Other test systems such as testing farm, packit, and zuul can't provide needed functionality, specifically test roles on all variations of supported composes and supported ansible versions.

**Comment by t184256** [comment]
> the first limitation is the PR is required to test the role

Can it reuse the last closed PR, maybe, if it's pointing at current HEAD? Just brainstorming.

> We need to report the results of testing somewhere that it is visible for both Red Hat and external contributors. The most convenient, and the only implemented way, for now, is through PR statuses.

Actions statuses themselves seems like the perfect candidate...

It was just last week when I've set up [scheduled pipelines](https://docs.gitlab.com/ee/ci/pipelines/schedules.html) on a couple of my GitLab errors and it has been so straightforward that this proposal to open 0-commit PRs weekly sounds awkward on so many levels in comparison...

**Comment by ukulekek** [comment]
> Can it reuse the last closed PR, maybe, if it's pointing at current HEAD? Just brainstorming.

No, the GitHub API doesn't allow to set statuses to a closed PR 

> Actions statuses themselves seems like the perfect candidate...

I failed to find any information about this. I only found docs about commit statuses which Ci currently uses https://docs.github.com/en/rest/commits/statuses#about-the-commit-statuses-api

**Comment by richm** [comment]
> > Can it reuse the last closed PR, maybe, if it's pointing at current HEAD? Just brainstorming.
> 
> No, the GitHub API doesn't allow to set statuses to a closed PR
> 
> > Actions statuses themselves seems like the perfect candidate...
> 
> I failed to find any information about this. I only found docs about commit statuses which Ci currently uses https://docs.github.com/en/rest/commits/statuses#about-the-commit-statuses-api

That will involve changes to the gluetool code, which will take some time.  In the meantime, this current approach gives us a lot of useful information now.

**Comment by t184256** [comment]
Not a fan, but you, gentlemen, seem insistent, so what can I do.

**Comment by ukulekek** [comment]
The PR is updated to the latest version @richm

**Review by richm — APPROVED** [review]

**Pull request merged**
