### PR TITLE
Emptying the skip list of .ansible-lint.

### PR DESCRIPTION
**Pull request by nhosoi**
Crypto_policy role is free from ansible-lint errors.

### CODE REVIEW

**Comment by richm** [comment]
Can you also fix the `208` error in tests/tests_include_vars_from_parent.yml ?

**Comment by nhosoi** [comment]
> Can you also fix the 208 error in tests/tests_include_vars_from_parent.yml ?

Sorry, I forgot about it... :( Adding it.

**Comment by richm** [comment]
@Jakuje do we need to do something else to enable rhel9 support? - from `rhel-x/ansible-2.9`: https://fedorapeople.org/groups/linuxsystemroles/logs/linux-system-roles-crypto_policies-pull-linux-system-roles_crypto_policies-18-52a355c-rhel-x-20210326-222714/artifacts/ansible.log
```
TASK [Check the current policy is DEFAULT and common variables] ****************
task path: /tmp/tmp5te0ydyh/tests/tests_default.yml:13
fatal: [/cache/rhel-x.qcow2]: FAILED! => {
    "assertion": "'NO-CAMELLIA' in crypto_policies_available_modules",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

**Review by richm — APPROVED** [review]
lgtm

**Comment by Jakuje** [comment]
> @Jakuje do we need to do something else to enable rhel9 support? - from `rhel-x/ansible-2.9`: https://fedorapeople.org/groups/linuxsystemroles/logs/linux-system-roles-crypto_policies-pull-linux-system-roles_crypto_policies-18-52a355c-rhel-x-20210326-222714/artifacts/ansible.log
> 
> ```
> TASK [Check the current policy is DEFAULT and common variables] ****************
> task path: /tmp/tmp5te0ydyh/tests/tests_default.yml:13
> fatal: [/cache/rhel-x.qcow2]: FAILED! => {
>     "assertion": "'NO-CAMELLIA' in crypto_policies_available_modules",
>     "changed": false,
>     "evaluated_to": false,
>     "msg": "Assertion failed"
> }
> ```

There are changes in the RHEL9 policies. We will need a different example here for RHEL9. Lets bring it in the new PR.

**Pull request merged**
